version: 2
updates:
  # Check for updates of actions every month.  Don't check crate updates,
  # because it creates way too many pull requests, and cargo update exists.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
