name: Release

on:
  push:
    # TODO: All relevant subcrate tags
    tags: v*

permissions: read-all

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # TODO create token in crates.io and add it as secret
      CARGO_REGISTRY_TOKEN: '${{ secrets.CARGO_REGISTRY_TOKEN }}'
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish --package logcontrol --no-verify
        if: ${{  startsWith(github.ref, 'refs/tags/logcontrol-v') }}
      - run: cargo publish --package log-reload --no-verify
        if: ${{  startsWith(github.ref, 'refs/tags/log-reload-v') }}
      - run: cargo publish --package logcontrol-log --no-verify
        if: ${{  startsWith(github.ref, 'refs/tags/logcontrol-log-v') }}
      - run: cargo publish --package logcontrol-zbus --no-verify
        if: ${{  startsWith(github.ref, 'refs/tags/logcontrol-zbus-v') }}
      - run: cargo publish --package logcontrol-tracing --no-verify
        if: ${{  startsWith(github.ref, 'refs/tags/logcontrol-tracing-v') }}
