name: "Test & Lint"

on:
  push:
    # Don't run CI for tags; there's always a branch for the tag as well so
    # there's no point in testing it separately
    tags-ignore: "*"
    branches: main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, "1.77.0"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt
      - run: cargo build --workspace --all-targets --locked
      - run: cargo clippy --workspace --all-targets --locked
      - run: cargo test --workspace --locked
      - run: cargo doc --workspace --locked
      - uses: EmbarkStudios/cargo-deny-action@v2
      - run: cargo fmt -- --check
